services:
  ip-blocklist:
    build:
      context: https://github.com/shineofrider/ip-blocklist.git

    container_name: ip-blocklist

    restart: unless-stopped

    environment:
      MAIL_PROTOCOL: imap

      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SSL: ${MAIL_SSL}

      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      POLL_INTERVAL: ${POLL_INTERVAL}
      RETENTION_DAYS: ${RETENTION_DAYS}

    volumes:
      - /opt/ip-blocklist/data:/data
      - /opt/ip-blocklist/exclusions.txt:/config/exclusions.txt:ro

    networks:
      - reverseproxy

networks:
  reverseproxy:
    external: true